package IntegrationTests;

import entity.*;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import service.BookingService;
import service.CarService;
import service.UserService;

import java.math.BigDecimal;
import java.time.LocalDate;

class BookingConnectionTest {

    BookingService bookingService;
    UserService userService;
    CarService carService;

    User testUser = new User("John");

    Car testCar = new Car("M5", "Ba129k", new BigDecimal("50.00"), Brand.BMW, true);

    @BeforeEach
    void setUp() {
        TestApplicationContext testInstance = TestApplicationContext.getInstance();

        bookingService = testInstance.getBookingService();
        userService = testInstance.getUserservice();
        carService = testInstance.getCarService();

        testUser = userService.createUser(testUser);
        testCar = carService.createCar(testCar);
    }

    @Test
    void testShouldCreateAndSaveBookingSuccessfully() {
        //Given
        LocalDate startDate = LocalDate.of(2026, 8, 15);
        LocalDate endDate = LocalDate.of(2026, 8, 20);

        Booking booking = new Booking(testUser, testCar, startDate, endDate, BookingStatus.ACTIVE);

        //When
        Booking result = bookingService.makeBooking(booking);

        Assertions.assertNotNull(result.getId(), "Id for booking must be generated by the repo");

        result = bookingService.getBookingRepository().findById(result.getId());

        //Then
        Assertions.assertNotNull(result, "Newly created booking not found in repo");

        Assertions.assertEquals(booking.getCar(), result.getCar());
        Assertions.assertEquals(booking.getUser(), result.getUser());
        Assertions.assertEquals(booking.getStartDate(), result.getStartDate());
        Assertions.assertEquals(booking.getEndDate(), result.getEndDate());
        Assertions.assertEquals(BookingStatus.ACTIVE, result.getStatus());
        Assertions.assertEquals(booking.getTotalPrice(), result.getTotalPrice());
    }
}