package IntegrationTests;

import entity.Brand;
import entity.Car;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import service.CarService;

import java.math.BigDecimal;

public class CarConnectionTest {

    CarService carService;

    @BeforeEach
    public void setUp() {
        TestApplicationContext testInstance = TestApplicationContext.getInstance();
        carService = testInstance.getCarService();

    }

    @Test
    public void testShouldSaveCarSuccessfully() {
        //Given
        Car testCar = new Car("C300", "A15DFT", new BigDecimal("55.32"), Brand.MERCEDES, true);

        //When
        Car result = carService.createCar(testCar);

        Assertions.assertNotNull(result.getId(), "Id must be generated by the repo");

        result = carService.getCarById(result.getId());

        //Then
        Assertions.assertNotNull(result, "Newly created car not found in repo");

        Assertions.assertEquals(testCar.getModel(), result.getModel());
        Assertions.assertEquals(testCar.getRegistrationNumber(), result.getRegistrationNumber());
        Assertions.assertEquals(testCar.getPricePerDay(), result.getPricePerDay());
        Assertions.assertEquals(testCar.getBrand(), result.getBrand());
        Assertions.assertEquals(testCar.isElectric(), result.isElectric());
        Assertions.assertEquals(testCar.isAvailable(), result.isAvailable());
    }
}